server:
  port: ${PORT:8080}

# H2 Database
spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    url: jdbc:h2:mem:dcbapp
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect